FROM golang:1.22 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/pubsub-worker ./pubsub/cmd/worker

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/pubsub-worker /pubsub-worker
ENTRYPOINT ["/pubsub-worker"]