FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/rabbit-worker ./rabbitmq/cmd/worker

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/rabbit-worker /rabbit-worker
ENTRYPOINT ["/rabbit-worker"]