FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/kafka-producer ./kafka/cmd/producer

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/kafka-producer /kafka-producer
ENTRYPOINT ["/kafka-producer"]